version: '3'
services:
  nginx-proxy:
        image: "jwilder/nginx-proxy:latest"
        container_name: "nginx-proxy"
        volumes:
            - "html:/usr/share/nginx/html"
            - "dhparam:/etc/nginx/dhparam"
            - "vhost:/etc/nginx/vhost.d"
            - "certs:/etc/nginx/certs"
            - "/run/docker.sock:/tmp/docker.sock:ro"
        restart: "always"
        networks: 
            - "everything_app"
        ports:
            - "80:80"
            - "443:443"
        environment:
            - DEFAULT_HOST=${DEFAULT_HOST}

  letsencrypt:
      image: "nginxproxy/acme-companion:latest"
      container_name: "letsencrypt-helper"
      volumes:
          - "html:/usr/share/nginx/html"
          - "dhparam:/etc/nginx/dhparam"
          - "vhost:/etc/nginx/vhost.d"
          - "certs:/etc/nginx/certs"
          - "/run/docker.sock:/var/run/docker.sock:ro"
      environment:
          - NGINX_PROXY_CONTAINER=${NGINX_PROXY_CONTAINER}
          - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
          - LETSENCRYPT_TEST=${LETSENCRYPT_TEST}
      restart: "always"
      depends_on:
          - "nginx-proxy"
      networks: 
          - "demo_default"
          
volumes:
  html: {}
  vhost: {}
  dhparam: {}
  certs: {}


networks:
  everything_app:
    name: everything_app
    external: true