FROM node
WORKDIR /app
COPY package.json .
RUN npm i
COPY . .

ENV VIRTUAL_HOST=${VIRTUAL_HOST_SECONDARY} \
    LETSENCRYPT_HOST=${LETSENCRYPT_HOST} \
    LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}


## EXPOSE [Port you mentioned in the vite.config file]
EXPOSE 5173
CMD ["npm", "run", "dev"]